name: Python Package using Pip

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Python syntax
      run: |
        python -m py_compile shizuchat/*.py || true
        echo "Python syntax check completed"
    - name: Display project info
      run: |
        echo "ShizuBot project successfully built!"
        echo "Python version: $(python --version)"
        echo "Dependencies installed successfully"
